[project]
name = "epic-help"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "beautifulsoup4>=4.13.3",
    "html2text>=2024.2.26",
    "markdown-it-py>=3.0.0",
    "markdownify>=1.1.0",
]
